### ISSUE TITLE
The query was never persisted to native form.

### ISSUE THREAD

**Issue by maroulu** [tomtom-international/tomtom-use-case-search-along-a-route-android#5]
Hi, the code bellow gives me the error in the title

SearchApi searchApi = OnlineSearchApi.create(this);
searchApi.reverseGeocoding(new ,ReverseGeocoderSearchQueryBuilder(location.getLatitude(),location.getLongitude()).build())
                .subscribeOn(Schedulers.newThread())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new DisposableSingleObserver<ReverseGeocoderSearchResponse>() {
                    @Override
                    public void onSuccess(ReverseGeocoderSearchResponse reverseGeocoderSearchResponse) {
                        pred.setAddress(reverseGeocoderSearchResponse.getAddresses().get(0).getAddress().getFreeformAddress());
                    }

                    @Override
                    public void onError(Throwable e) {

                    }
                });

**Comment by szczepanczyk** [comment]
Hi. 
Unfortunatelly this is a bug in the newest version of our Search SDK (2.404). It will be fixed in next release. To make it work, you can use a function which takes a `RevGeoSearchResultListener` as a second parameter instead of the one which returns a `Single<ReverseGeocoderSearchResponse>`. If you have to use Rx version of the `reverseGeocoding` function, than you can use previous version of our SDK (2.364) and update it after the bug will be fixed.

**Comment by maroulu** [comment]
can you help me to adapt my code to the listener

**Comment by szczepanczyk** [comment]
```
ReverseGeocoderSearchQuery query = new ReverseGeocoderSearchQueryBuilder(location.getLatitude(), location.getLongitude()).build();
searchApi.reverseGeocoding(query, new RevGeoSearchResultListener() {
    @Override
    public void onSearchResult(ReverseGeocoderSearchResponse reverseGeocoderSearchResponse) {
      //TODO
    }
    @Override
    public void onSearchError(SearchError searchError) {
      //TODO
    }
  });
}
```
